[tool.poetry]
name = "lamutual-project"
version = "0.1.0"
description = "Î›mutual core with clean CI (Ark launch)"
authors = ["Amutual Crew <team@example.com>"]
readme = "README.md"
packages = [{include = "lamutual_project"}]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
ruff = "^0.5.0"
jsonschema = "^4.22.0"

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py311"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
