name: Main CI

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Configure PATH and PYTHONPATH
        run: |
          echo "PYTHONPATH=${GITHUB_WORKSPACE}/lamutual_project" >> $GITHUB_ENV
          echo "${GITHUB_WORKSPACE}/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry --version
          poetry install --no-interaction

      - name: Run tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
          HEART_PROTOCOL_SALT: ${{ secrets.HEART_PROTOCOL_SALT }}
        run: |
          if [ -z "${HEART_PROTOCOL_SALT:-}" ]; then
            echo "::warning::HEART_PROTOCOL_SALT is not set; tests requiring it may be skipped or fail."
          fi
          poetry run pytest -q
